config/routes.rb
 Rails.application.routes.draw do
  get 'user/index'
  get 'tags/:tag', to: 'albums#index', as: :tag

  devise_for :users

   root 'albums#new'

 resources :pictures

   resources :albums
     resources :albums do
        resources :pictures
     end

end

app/models/album.rb
class Album < ActiveRecord::Base
 acts_as_paranoid
belongs_to :user
has_many :pictures
acts_as_taggable
has_attached_file :photo
validates_attachment_presence :photo
accepts_nested_attributes_for :pictures
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/picture.rb
class Picture < ActiveRecord::Base
belongs_to :user
belongs_to :album
has_attached_file :avatar
validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :albums

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album =Album.new
  end

  def create
    @album = current_user.albums.new(album_params)
    if @album.save
      redirect_to @album
    else
     render 'new'
   end
  end

  
  def index
    if params[:tag]
    @album = Album.tagged_with(params[:tag])
  else
    @album = Album.all
  end
  end
  
  
  def show
    @album = Album.find(params[:id])
    
  end
  
  def edit
    @album = Album.find(params[:id])
  end
  def destroy
   
@album = Album.find(params[:id])
     @album.destroy
     respond_to do |format|
     format.html { redirect_to albums_url }
     format.json { head :no_content }
     format.js   { render :layout => false }
   #  Album.restore(@album.id, recursive: true)
   
  end
end
  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to @album
    else
     render 'edit'
  end
  end
  end
 private
  def album_params
    params.require(:album).permit(:title, :description, :photo, :tag_list, :time_at)
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
before_action :authenticate_user!
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

def new
 @album = Album.find(params[:album_id])
end

def create
    @album = Album.find(params[:album_id])
    @picture = @album.pictures.create(picture_params)
    redirect_to album_path(@album)
  end
  def destroy
    @album = Album.find(params[:album_id])
    @picture = @album.pictures.find(params[:id])
    @picture.destroy
    debugger
    redirect_to album_path(@album)
  end
  def show
   @picture = Picture.find(params[:id])
   end
def index
  @picture = Picture.where(album_id: (params[:album_id]))
end
  private
    def picture_params
      params.require(:picture).permit(:avatar)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @user = User.new
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/albums/_form.html.erb
<%= form_for @album, :html => { :multipart => true } do |f| %>

  <p>
    <%= f.label :TITLE %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :DESCRIPTION %><br>
    <%= f.text_field :description %>
  </p>


<p>

  <%= f.label :tag_list, "Tags (separated by commas)" %><br />
  <%= f.text_field :tag_list %>
</p>


 <p>
     <%= f.file_field :photo %>
  </p>
  <p>
<%=f.time_select(:time_at,:default => Time.now.change(:hour => 8),:start_hour => 8, :end_hour => 20, :ampm => true)%>
</p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/albums/destroy.js.erb
$('.destroy_album').bind('ajax:success', function() {  
       $(this).closest('tr').fadeOut();
});

app/views/albums/edit.html.erb
<h1>Edit album</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h2>Here are Your Albums</h2>
<%= link_to 'New album', new_album_path %>
<center>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Image</th>
  </tr>

  <% @album.each do |album| %>
    <tr>
      <td><%= album.title %></td>
      <td><%= album.description %></td>
     <td> <%= image_tag album.photo.url %></td>



 

<td>Tags: <%= raw album.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
     <td> <%= link_to 'Add Photo to Album', new_album_picture_path(album) %><br />
<%= link_to 'Show Album', album_pictures_path(album) %><br />
<%= link_to 'Edit', edit_album_path(album) %><br />

<%= link_to 'Destroy', album_path(album),
              method: :delete,
              data: { confirm: 'Are you sure?' } %> </td></br>
</tr>
<% end %>
</table>
<%= link_to 'Back', albums_path %> 



    
  

</center>

app/views/albums/index.html.haml
<h2>Here are Your Albums</h2>
<%= link_to 'New album', new_album_path %>
<center>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Image</th>
  </tr>

  <% @album.each do |album| %>
    <tr>
      <td><%= album.title %></td>
      <td><%= album.description %></td>
     <td> <%= image_tag album.photo.url %></td>



 

<td>Tags: <%= raw album.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
     <td> <%= link_to 'Add Photo to Album', new_album_picture_path(album) %><br />
<%= link_to 'Show Album', album_pictures_path(album) %><br />
<%= link_to 'Edit', edit_album_path(album) %><br />

<%= link_to 'Destroy', album_path(album),
              method: :delete,
              data: { confirm: 'Are you sure?' } %> </td></br>
</tr>
<% end %>
</table>
<%= link_to 'Back', albums_path %> 



    
  

</center>

app/views/albums/new.html.erb
<h1>NEW ALBUM</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p>
  <strong>TITLE:</strong>

  <%= @album.title %> 
</p>

<p>
  <strong>DESCRIPTION:</strong>
  <%= @album.description %>
</p>
 <p> <%= image_tag @album.photo.url %>
 </p>
 <p> Album created at:<%= @album.time_at %> 
     </p>
<%= link_to 'Back', albums_path %>
<%= link_to 'Edit', edit_album_path(@album) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webalbums</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h2><center>Welcome to Web Album</center></h2>
<p class='log'>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Logout", destroy_user_session_path %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
<%= yield %>

</body>
</html>

app/views/pictures/index.html.erb
<% @picture.each do |f| %>
<%= image_tag f.avatar.url %>

<% end %>

<td><%= link_to 'Back to Album', albums_path(@album) %></td>

app/views/pictures/new.html.erb
<%= form_for([@album, @album.pictures.build]) do |f| %>
<p><h1>ADD YOUR PHOTO HERE</h1></p>
 <p>
    <%= f.file_field :avatar %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/pictures/show.html.erb
<% @picture.each do |f| %>
<%= image_tag @album.photo.url %>
<% end %>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>